### ISSUE TITLE
always show the workspace in the bottom and never disappear. 

### ISSUE THREAD

**Issue by wqhhust** [wasamasa/eyebrowse#39] opened 2015-09-10 09:22 UTC
After I type Space+W in spacemacs, it show the workspace in the bottom as below snapshot.
![image](https://cloud.githubusercontent.com/assets/5955201/9784779/6dd0161a-577b-11e5-925f-73384028e32c.png)

But it could be better to keep it in the bottom. I have the following bind.And then I tag each workspace, so I could easily switch between window. But if it disappear, I only know the number of the window, if it could not disappear, then I could know which window has which tag and do quick switch.
  (global-set-key (kbd "C-1") 'eyebrowse-switch-to-window-config-1)
  (global-set-key (kbd "C-2") 'eyebrowse-switch-to-window-config-2)
  (global-set-key (kbd "C-3") 'eyebrowse-switch-to-window-config-3)
  (global-set-key (kbd "C-4") 'eyebrowse-switch-to-window-config-4)
  (global-set-key (kbd "C-5") 'eyebrowse-switch-to-window-config-5)
  (global-set-key (kbd "C-6") 'eyebrowse-switch-to-window-config-6)
  (global-set-key (kbd "C-7") 'eyebrowse-switch-to-window-config-7)

**Comment by wasamasa** [comment] 2015-09-10 11:47
Did you try customizing `eyebrowse-mode-line-style`?

**Comment by wasamasa** [comment] 2015-09-10 12:25
Did you try customizing `eyebrowse-mode-line-style`?

**Comment by syl20bnr** [comment] 2015-09-10 12:52
Please open the issue on Spacemacs repo first or ask on the chat ;-)

The eyebrowse layer uses micro-state instead of the mode-line, this is by design. A new modeline API will be in the next release to easily define modeline segments and place it where you want, it is available on develop as well as the documentation in DOCUMENTATION.org

**Comment by wasamasa** [comment] 2015-09-10 13:33
@syl20bnr Thanks for clarification, I suspected something of this kind, but wasn't sure.

Closing.

**Closed by wasamasa** 2015-09-10 13:33 UTC
