### ISSUE TITLE
New workspaces with *Scratch* as default buffer

### ISSUE THREAD

**Issue by eubarbosa** [wasamasa/eyebrowse#98] opened 2018-12-27 00:58 UTC
Hi,

Its probably possible achievable with add-advice...

Still,  I think most users would expect eyebrowse workspaces to behave like DE/WM newly created workspaces with wallpaper as its background.

Just a humble feedback!  :+1:

**Comment by wasamasa** [comment] 2018-12-27 12:19
This is a duplicate of #23

**Closed by wasamasa** 2018-12-27 12:19 UTC

**Comment by eubarbosa** [comment] 2018-12-27 12:36
LOL, I beg your pardon! Thanks!
