### ISSUE TITLE
After eyebrowse-close-window-config, eyebrowse-prev/next-window-config creates an extra copy of current window config

### ISSUE THREAD

**Issue by yurikoif** [wasamasa/eyebrowse#111] opened 2019-09-26 20:24 UTC
Run eyebrowse-create-window-config:
![image](https://user-images.githubusercontent.com/10281921/65722180-b7c02b80-e079-11e9-89b0-a32a791c7675.png)
Run eyebrowse-close-window-config:
![image](https://user-images.githubusercontent.com/10281921/65722230-d9b9ae00-e079-11e9-88f4-68aae854044d.png)
Run eyebrowse-next/prev-window-config:
![image](https://user-images.githubusercontent.com/10281921/65722297-0241a800-e07a-11e9-988a-c7679b5fdf16.png)
Notice that the last result should be identical to the last second, but it creates another extra window config like in the first.
Emacs version: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-09-13
Eyebrowse version: eyebrowse-20190917.1653

**Comment by wasamasa** [comment] 2019-09-28 14:59
I've debugged this a bit and noticed this only happens when both `eyebrowse-wrap-around` and `eyebrowse-switch-back-and-forth` are set:

- There is no window config after the current one to switch to
- `eyebrowse-wrap-around` is set, so switch to the first one
- `eyebrowse-switch-back-and-forth` is set, so switch to the last one
- The last one was numbered 2
- There is no such window config, so create a new one at that index (by default a duplicate of the current one)

I've added a change to both `eyebrowse-next/-prev-window-config` to check whether there's more than one window configuration before trying to switch to the previous/next window config.

**Closed by wasamasa** 2019-09-28 14:59 UTC
